module.exports = {
    uthome:'/pages/usercenterindex/usercenter.html',
    jfindex:'http://jf.10get.com',
    jfHTML:'<ul class="order_menu"><li class="hover" ><a href="../orderList/orderList.html">官方商城</a></li><li><a href="http://jf.10get.com/account/buyer/order.html" id="jf-tab-listen">积分商城</a></li></ul><p class="zqstate tab-switch"><a href="#" class="active all">全部订单</a><a href="#" class="waitpay">待付款<span id="waitpaycount">(0)</span></a><a href="#" class="waitship">待发货<span id="waitshippingcount">(0)</span></a><a href="#" class="shipping">待收货 <span id="shippingcount">(0)</span></a><a href="#" class="waitcomment">待评价 <span id="waitcommentcount">(0)</span></a><a href="#" class="succeed">已完成<span id="succeedorder">(0)</span></a><a href="javascript:;" class="delete"><span href="javascript:;" class="del-order"></span>订单回收站</a><a href="#" class="closed">已关闭</a></p>',
    aftersaleHTML:'<ul class="order_menu"><li class="hover" ><a href="../aftersale/aftersale.html">官网订单</a></li><li><a id="jf-tab-listen" href="http://jf.10get.com/account/refundbuyer/buyer.html">积分商城订单</a></li></ul>',
    jforder:'http://jf.10get.com/account/buyer/order.html',
    fapiao:'http://testuser.tclo2o.cn/proxy/invoice/vat/list',
    wodejf:'http://testuser.tclo2o.cn/proxy/integral',
    wodequanyi:'http://testuser.tclo2o.cn/proxy/equity/index',
    wodeshoucang:'/pages/collect/collects.html#collects',
    wodezuji:'/pages/footmark/footermarklist.html#footermarklist',
    myproduct:'http://jf.10get.com/account/product/myproduct.html',
    fuwujilu:'http://testuser.tclo2o.cn/proxy/service/record/query',
    shequzhongxin:'http://www.t-fans.net',
    shequtongzhi:'http://www.t-fans.net/home.php?mod=space&do=pm',
    woderenzheng:'http://www.t-fans.net/home.php?mod=spacecp&ac=profile&op=verify',
    account:'http://testuser.tclo2o.cn/proxy/accountsafe',
    address:'http://testuser.tclo2o.cn/proxy/address/shipping/list',
    reg:'http://testuser.tclo2o.cn/proxy/register',
    login:'/sign',
    userCenterBar:'../../app/plugins/userCenterBar/unfiyCenterBar.html',
    accountsafe: 'http://testuser.tclo2o.cn/proxy/accountsafe',
    integral: 'http://testuser.tclo2o.cn/proxy/integral',
    manageuser: '/pages/usercenterindex/usercenter.html',
    /*equityHTML:'<a href="http://jf.10get.com/account/product/myproduct.html"><span>我的产品<span></span></a><a href="http://testuser.tclo2o.cn/proxy/equity/index"><span>我的权益<span></span></a>',*/
    equityHTML:'',
    sso:"http://testuser.tclo2o.cn/sso/account/verifyUsernameToken?client_id=14046695&funcName=cb&_="+Math.random(),
    regBulk:'notLoginUnTest',
}
